"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from panora import utils
from typing import List


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class RemoteThirdPartyCreationDto:
    id_connection: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id_connection') }})
    mw_ids: List[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('mw_ids') }})
    

