"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import httpmetadata as components_httpmetadata
from ...models.components import passthroughrequestdto as components_passthroughrequestdto
from ...models.components import passthroughresponse as components_passthroughresponse
from dataclasses_json import Undefined, dataclass_json
from typing import Optional


@dataclasses.dataclass
class PassthroughRequestRequest:
    integration_id: str = dataclasses.field(metadata={'query_param': { 'field_name': 'integrationId', 'style': 'form', 'explode': True }})
    linked_user_id: str = dataclasses.field(metadata={'query_param': { 'field_name': 'linkedUserId', 'style': 'form', 'explode': True }})
    vertical: str = dataclasses.field(metadata={'query_param': { 'field_name': 'vertical', 'style': 'form', 'explode': True }})
    pass_through_request_dto: components_passthroughrequestdto.PassThroughRequestDto = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PassthroughRequestResponse:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field(metadata={'dataclasses_json': { 'exclude': lambda f: True }})
    pass_through_response: Optional[components_passthroughresponse.PassThroughResponse] = dataclasses.field(default=None)
    

